### ISSUE TITLE
Enable 2FA support for the auto login flow

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/protonmail-desktop-app#10]
2FA support context menu is released with v0.3.0

Here is how to configure it:

![2fa](https://user-images.githubusercontent.com/1560781/35880339-f53c90d4-0b7d-11e8-87fb-753d26a93128.png)

**Comment by vladimiry** [comment]
Don't forget to add that key to your phone, and save the recovery codes somewhere.

**Comment by HenrijsS** [comment]
Sorry for writing on a closed issue, but I just had a general question.
I'm using dual-boot Win/Linux. 
The only way for me to get the Two-Factor secret key from Proton seems to be if I remove it and add again.
Is there an option to just get the secret key without disabling the TFA?

**Comment by vladimiry** [comment]
>  The only way for me to get the Two-Factor secret key from Proton seems to be if I remove it and add again.

A few years back when I was handling this issue it worker the way you described. It's likely still working the same way.

>  Is there an option to just get the secret key without disabling the TFA?

It's unlikely the @protonmail provides such option, you could ask them/support though.

**Comment by vladimiry** [comment]
@HenrijsS by the way consider enabling the [persistent session](https://github.com/vladimiry/ElectronMail/issues/227) feature. So you don't save any credentials in the app but still get the fully automated signing into the accounts.

**Comment by HenrijsS** [comment]
@vladimiry Thank you for the quick answer. I'll try to get in touch with Protonmail about this. Maybe there's a way to get it. 
Seeing as in the Account settings on EM, the key is hidden. Is it accessible with the Master Password maybe?

**Comment by vladimiry** [comment]
You can see in https://github.com/vladimiry/ElectronMail/issues/318#issuecomment-678121062 how to decrypt the raw credentials values knowing the master password.
