### ISSUE TITLE
No copy and paste functionality?

### ISSUE THREAD

**Issue by harrisondesbrosses** [vladimiry/protonmail-desktop-app#11]
Am I the only one experiencing a total lack of copy and paste functionality? It's definitely annoying for password input, but mostly for day to day copying of peoples words in emails...

**Comment by vladimiry** [comment]
It might be because you are the only one who is using this app :smile: Copy-pasting is not enabled at the moment.

**Comment by harrisondesbrosses** [comment]
Haha! Well I find it very useful for OPSEC reasons - I run a hackintosh and cannot enable filevault on the drive - so all mails must be kept on another, encrypted drive... this app solves that problem for me.

Such a good, accidental feature of your app!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by vladimiry** [comment]
Basic context menu is releases with v0.3.0

**Comment by harrisondesbrosses** [comment]
Running OS X 10.11.6 on a hackintosh (Clover)
See link for screengrab video of problem - https://nofile.io/f/WoJn8tAKjY2/protonmaildesktop_issue_11.mov

**Comment by vladimiry** [comment]
Thanks for report. I enabled context menu only for the ProtonMail's webviews (same content the you see opening https://mail.protonmail.com/login), ie only for the emails stuff, but not for the app itself. I thought that was a need. It's not a big deal to enable context menu for the app itself (outer window), going to do that. On Linux inserting master password works by the way using default ctrl+v hotkey.

**Comment by vladimiry** [comment]
@harrisondesbrosses can you try and confirm that [protonmail-desktop-app-0.3.1](https://www.dropbox.com/sh/esir9qhti6nl8k8/AABEJSgfxy-gdudwXBgldZwDa?dl=0) works as expected. It enables such menu for the main app window (same menu was enabled for email windows by previous commit):

![context menu](https://user-images.githubusercontent.com/1560781/35929010-c8786526-0c2e-11e8-932e-abe3cb8b02eb.jpg)

**Comment by vladimiry** [comment]
Closing as resolved, v0.3.1 release has been published. Feel free to reach out if some functionality is still missing.
