### ISSUE TITLE
macOS specific issues

### ISSUE THREAD

**Issue by joshirio** [vladimiry/protonmail-desktop-app#24]
Hello, thanks for this app, works great on linux and I like the auto-login feature which other alternative community protonmail electron apps don't provide. I'm looking to make an AUR package for it (Manjaro, Antergos and Arch).

Now, I noticed that on macOS there are a few issues:
1. The tray icon is too big:
![tray](https://user-images.githubusercontent.com/12795018/40077102-e7bf83b2-5880-11e8-9356-959557924b7c.png)

2. Context menu (right click action) shows the menu for half a second and then it disappears and copy/pasting (via cmd + c/v) is not possible on the settings page:
<img width="556" alt="context menu and copypaste" src="https://user-images.githubusercontent.com/12795018/40077241-51613d60-5881-11e8-93bf-2132448253b7.png">

3. Multiple accounts don't work on macOS, the second account shows a blank page, looks like it's stuck while logging in:
<img width="600" alt="2ndaccount" src="https://user-images.githubusercontent.com/12795018/40077344-ad756522-5881-11e8-9772-85d52b595d90.png">

Keep it up, nice work so far.

**Comment by vladimiry** [comment]
Hi @joshirio, thanks for the detailed report. It's good to know that someone has tried to run the app on macOS, so we got some issues revealed :) I was able to reproduce the described issues running macOS under a virtual machine, that's a first step of fixing them.

**Comment by vladimiry** [comment]
@joshirio can you test this version https://www.dropbox.com/s/2uvpaqf8k1mwbau/protonmail-desktop-app-0.4.1-mac.dmg?dl=1?

**Comment by vladimiry** [comment]
New link (gets back app window  context menu creating) https://www.dropbox.com/s/q52uk0s12njbrz8/protonmail-desktop-app-0.4.1-mac.dmg?dl=1

**Comment by vladimiry** [comment]
Can you test this version https://www.dropbox.com/s/wyd226d6c6050ha/protonmail-desktop-app-0.4.1-mac.dmg?dl=1 ? It includes all the needed fixes.

**Comment by joshirio** [comment]
that was quick :)
yes everything works as expected now, thanks a lot.

As an ultimate suggestion to make the app fit well inside macOS would be to have a notification badge on the dock, [I think electron has this feature included](https://stackoverflow.com/questions/31813947/how-to-implement-a-dock-icon-notification-indicator-with-electron-in-os-x).

**Comment by vladimiry** [comment]
> I'm looking to make an AUR package for it (Manjaro, Antergos and Arch).

@joshirio thanks for maintaining [email-securely-app-bin](https://aur.archlinux.org/packages/email-securely-app-bin/) in AUR as well.
