### ISSUE TITLE
Desktop notifications not working 

### ISSUE THREAD

**Issue by Ghost-Recon131** [vladimiry/protonmail-desktop-app#28]
Hello, for the desktop notifications on Windows 10 doesn't appear to be working. When I receive an email, there will be a little red circle on the app's icon on the taskbar. However, there is no desktop notification like ones windows give through notification centre. Is this a bug? I have enabled the "Unread messages desktop notifications" settings and I do not have Do not disturb on windows turned on.

**Comment by Ghost-Recon131** [comment]
thanks for the reply and keep up the good work :)

**Comment by vladimiry** [comment]
@Ghost-Recon131 can you try this version https://www.dropbox.com/s/jiycitmwvgka18w/protonmail-desktop-app-0.4.3-windows-nsis-installer.exe?dl=1 ? Will publish new release if notifications got working with it.

**Comment by Ghost-Recon131** [comment]
Thanks for the quick update, this new version works and gives a notification through Window's notification centre.

**Comment by vladimiry** [comment]
Thanks for testing and confirming that it works well now, [v0.4.3 release](https://github.com/vladimiry/protonmail-desktop-app/releases/tag/v0.4.3) with this fix included has been published.

**Comment by Ghost-Recon131** [comment]
Sorry for me being picky but in the next update, could you make the new mail notification stick in the notification centre instead of appearing on the side for 10-15sec then disappear? thx!

**Comment by vladimiry** [comment]
It's a system notification, and so it work as such on different systems. As far as I know there is no such option on Windows OS as specifying different notification position for different programs.

**Comment by Ghost-Recon131** [comment]
Sorry to keep bugging you, what's the difference between the different key deviation presets and Encryption preset? Which would be the most secure setting? Also if you don't mind, could you digitally sign the installers? Windows will block the install unless I manually allow it. It said something along the lines of "Program is unrecognised and windows SmartScreen has prevented it from running." 
Thanks for the good work!

**Comment by vladimiry** [comment]
It's key derivation, not a deviation. You can look into the Wikipedia, this is a quite general topic.

- I will note first that I don't consider myself as a security expert. Any kind of experts are welcomed to jump into and review the code, it's an open source stuff.
- Normally encryption algorithms require a key of a specific length, depending on the algorithm. So we need to have a key to be able to encrypt/decrypt something, not just a password.
- Key derivation is a function of deriving a key from the password. So for example even if your password let's say 3 characters length, key derivation function will produce a key of the constant length required by a specific encryption algorithm (like 16-byte length key).
- Speaking of a single specific key derivation function, the higher work factor, the better security, as a brute force like attacks will take more hardware resources and respectively more time. There is a hint app displays near to the related options list:

![hint](https://user-images.githubusercontent.com/1560781/42758442-359a3f30-890c-11e8-9705-9b1c87d40918.png)

As for the code signing, it's possible to do, but I'm not going to do that in the near future. This is a [page](https://www.electron.build/code-signing/) related to the topic.
