### ISSUE TITLE
temporary node file with random name

### ISSUE THREAD

**Issue by ask2018** [vladimiry/protonmail-desktop-app#5]
Hi, I'm trying this software on Win 7 64bit and this software is creating on every start new temp .node file in the windows temp folder. Problem is this file is temporary binary executable file with random file name and that's the reason I cannot create for it proper rules in my security software. It's simply new file again and again and I need to create/confirm these rules again and again. Is there chance to change this behaviour in future builds?

**Comment by vladimiry** [comment]
@ask2018 can you this version https://github.com/vladimiry/protonmail-desktop-app/releases/tag/v0.2.1

**Comment by ask2018** [comment]
Thanks for update, but unfortunately it's still the same with 0.2.1 version. On every new software start file "C:\Users\USERNAME\AppData\Local\Temp\some_random_string.tmp.node" is created and because this seems to be some DLL file, my security software keeps asking me for updated/new component confirmation with my current security settings. Basically what I need is no temp executable files with random name like this created and using just usual static location/filename executables and other components.

**Comment by vladimiry** [comment]
That tmp file is a native library (yes apparently DLL like) that comes with https://github.com/atom/node-keytar module. You can unpack `asar` close to app executable manually an make sure that tmp file and `keytar`'s binary module are equal files. Electron unpacks it for execution/loading from `asar` archive. I disabled `keytar` module packaging assuming that it will be sufficient fix, but that was just a quick guess. I might come up with new ideas, but that's how things work for now.

**Comment by vladimiry** [comment]
> I disabled keytar module packaging assuming that it will be sufficient fix, but that was just a quick guess.

> First of all I will need to verify that keytar module has not actually been packed into the asar with 0.2.1 version.

Unpacking modules with native code was a right move, I just failed to properly unpack it, fix is coming.

**Comment by vladimiry** [comment]
@ask2018 can you verify that issue has been resolved with new release https://github.com/vladimiry/protonmail-desktop-app/releases/tag/v0.2.2v

**Comment by ask2018** [comment]
Yeah great. Thank you. Seems to be fixed. No more temp files created.Tested protonmail-desktop-app-Setup-0.2.2.exe only. The NSIS installer for version 0.2.2 seems to be broken and just crash after I try to run it: Btw would be also nice to let the user to choose custom installation folder and my personal suggestion for installation program is Inno Setup - http://www.jrsoftware.org/isinfo.php That's much more cleaner setups in my opinion.

**Comment by vladimiry** [comment]
Closing as resolved.

Adjusting installation packages is a different thing.

> let the user to choose custom installation folder

Available in 0.2.3.
