### ISSUE TITLE
NSIS installer crashes

### ISSUE THREAD

**Issue by ask2018** [vladimiry/protonmail-desktop-app#6]
NSIS installer is still broken in version 0.2.3. In version 0.2.2 the crash was immediately after I tried to run the exe. In version 0.2.3 the crash is after I click "next" if option "Only for me (username)" is selected. And weird thing is, if I choose "Anyone who uses this computer (all users)", then click next, then click back, change to "Only for me (username)" and click "next" again, then there is no crash.

**Comment by vladimiry** [comment]
Can you try to do the same on clean machine or with at least having your
antiviruse like tools switched off. I guess its about your specific
envitinment setup. Meanwhile going to reproduce a described case on Win 10.

**Comment by ask2018** [comment]
I don't have here any other system with compatible Windows OS to test it and doesn't look like it's AV related problem. I did few more tests and noticed the crash is not here if I move the installation program to other location on my drive.
Original location where I noticed the crash was D:\Download, then copied to D:\Download\test and no crash, then again run from D:\Download and crash again, but not in every case. Really weird behaviour.
protonmail-desktop-app-0.2.4-windows.exe works fine. But that version just installs it without asking for anything and there is not the screen where the crash occurs. Also version 0.2.1 and 0.2.0-beta.2 was without the crash before.
But I simply unpacked the installer with 7zip and copied the files manually and everything works just fine. So if you cannot reproduce it and nobody else will report this issue, just leave it, it's not so big deal for me if the installer can be easily unpacked and files copied manually like in this case.
My OS is Win 7 Enterprise x64 SP1, all security updates installed, but really lot of custom settings here. So yes it might be some specific problem related to something in my OS. But hard to say what exactly.

**Comment by vladimiry** [comment]
Thanks for the detailed report, I'm going to forward it to the `electron-builder`'s issue tracker, this particular issue https://github.com/electron-userland/electron-builder/issues/2518.

Closing this issue as code in this repository doesn't directly manage the installing packages preparing. Issue resolving progress tracking can be seen here https://github.com/electron-userland/electron-builder/issues/2518
